# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
	config.vm.provider :virtualbox do |vb,override|
		config.vm.hostname="sample-vagrant"
		config.vm.box = "precise32"
		config.vm.box_url="http://files.vagrantup.com/precise32.box"
	end	

	config.vm.provision :shell, :path => "ansible/scripts/ansible_setup.sh"
	config.vm.provision :shell, :path => "ansible/scripts/key_setup.sh"
	config.vm.provision :shell, :inline => "export ANSIBLE_CONFIG=/vagrant/ansible.cfg; ansible-playbook -i '127.0.0.1,' /vagrant/mysetup.yml", :privilege => false
end
