---
 - name: download vagrant 1.2.2
   command: wget -P /tmp/ http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/vagrant_1.2.2_x86_64.deb

 - name: install vagrant using dpkg
   command: dpkg -i /tmp/vagrant_1.2.2_x86_64.deb

 - name: install vagrant aws plugin
   command: vagrant plugin install vagrant-aws

 - name: add dummy.box for aws instance
   command: vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
