# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.provider :virtualbox do |vb, override|
    config.vm.hostname="aptly"
    config.vm.box = "trusty64"
  end
  config.vm.network :private_network, ip: "192.168.50.5"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "aptly.yml"
    ansible.verbose='vvv'
  end
end
