---
 - name: Add aptly repository key
   apt_key: keyserver=keys.gnupg.net id=E083A3782A194991 state=present
 
 - name: Add aptly repository
   apt_repository: repo='deb http://repo.aptly.info/ squeeze main' state=present update_cache=yes

 - name: Install Aptly
   apt: name=aptly state=present
