---
 - name: Add aptly repository key
   apt_key: keyserver=keys.gnupg.net id=E083A3782A194991 state=present
 
 - name: Add aptly repository
   apt_repository: repo='deb http://repo.aptly.info/ squeeze main' state=present update_cache=yes

 - name: Install Aptly
   apt: name=aptly state=present

 - name: update sample app package
   become: vagrant
   copy: src=sample_app_1.0_all.deb dest=/tmp/

 - name: create same app repostiory
   become: vagrant
   shell: aptly repo create sample-app

 - name: add sample deb package
   become: vagrant
   shell: aptly repo add sample-app /tmp/sample_app_1.0_all.deb

 - name: publish sample-app repo
   become: vagrant
   shell: aptly --skip-signing -architectures='amd64' -distribution="`lsb_release -cs`" publish repo sample-app sample-app

 - name: add gpg key for sensu-mirror
   become: vagrant
   shell: gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7580C77F

 - name: add sample sensu mirror
   become: vagrant
   shell: aptly -architectures='amd64' -filter='sensu (>=0.20.1)' mirror create sensu-mirror http://repos.sensuapp.org/apt sensu main

 - name: update sample sensu mirror
   become: vagrant
   shell: aptly mirror update sensu-mirror

 - name: Install nginx
   apt: name=nginx state=present

 - name: remove nginx default page
   file: path=/etc/nginx/sites-enabled/default state=absent

 - name: replace with custom nginx config
   copy: src=nginx-aptly.conf dest=/etc/nginx/sites-available/aptly.conf owner=root group=root mode=644

 - name: use custom nginx.conf instead
   file: src=nginx.conf dest=/etc/nginx/nginx.conf

 - name: create symlink to config
   file: src=/etc/nginx/sites-available/aptly.conf dest=/etc/nginx/sites-enabled/aptly.conf state=link
   notify: reload nginx

 - name: create prod latest foler
   file: path=/home/vagrant/production/latest state=directory

 - name: create dev latest folder
   file: path=/home/vagrant/dev/latest state=directory
