# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
	config.vm.provider :virtualbox do |vb,override|
		config.vm.hostname="pelican-vagrant"
		config.vm.box = "precise32"
		config.vm.box_url="http://files.vagrantup.com/precise32.box"
		config.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)"
		config.vm.network :forwarded_port, guest: 80, host: 2111
	end	

	config.vm.provision "puppet" do |puppet|
		puppet.manifests_path="puppet/manifests"
		puppet.manifest_file="pelican.pp"
		puppet.module_path="puppet/modules"
	end
end
