---
 - name: install zsh and curl
   sudo: yes
   apt: pkg={{item}} state=present
   with_items:
    - zsh
    - curl
    - git

 - name: make sure .oh-my-zsh folder exist
   file: path=/home/{{item}}/.oh-my-zsh owner={{item}} group={{item}} state=directory
   with_items: users

 - name: clone oh-my-zsh repo
   git: repo=git://github.com/robbyrussell/oh-my-zsh.git  dest=/home/{{item}}/.oh-my-zsh
   with_items: users

 - name: create zsh config
   copy: src=/home/{{item}}/.oh-my-zsh/templates/zshrc.zsh-template  dest=/home/{{item}}/.zshrc owner={{item}}
   with_items: users

 - name: chsh
   sudo: yes
   command: /usr/bin/chsh -s /bin/zsh {{item}}
   with_items: users

 - name: this should be in git for setting alias
   template: src=gitconfig.j2 dest=/home/{{item}}/.gitconfig
   with_items: users
